export const BURGERS = [
    {
        id: 1,
        name: 'Classic Burger',
        patty: 'Beef',
        cheese: true,
        lettuce: true,
        tomato: true,
        onion: false,
        sauce: true,
        price: 5.99,
        calories: 450,
        inStock: true,
        description: 'A classic beef burger with cheese, lettuce, tomato, and a tangy sauce.'
    },
    {
        id: 2,
        name: 'Veggie Delight',
        patty: 'Veggie',
        cheese: false,
        lettuce: true,
        tomato: true,
        onion: false,
        sauce: false,
        price: 4.99,
        calories: 350,
        inStock: true,
        description: 'A light and fresh veggie burger with lettuce and tomato.'
    },
    {
        id: 3,
        name: 'Cheese Lover',
        patty: 'Chicken',
        cheese: true,
        lettuce: false,
        tomato: true,
        onion: true,
        sauce: true,
        price: 6.49,
        calories: 500,
        inStock: true,
        description: 'A juicy chicken patty topped with melted cheese, tomato, onion, and a spicy sauce.'
    },
    {
        id: 4,
        name: 'Bacon Burger',
        patty: 'Beef',
        cheese: true,
        lettuce: true,
        tomato: true,
        onion: true,
        sauce: true,
        price: 7.99,
        calories: 700,
        inStock: false,
        description: 'A hearty beef patty with cheese, crispy bacon, and all the classic toppings.'
    },
    {
        id: 5,
        name: 'BBQ Chicken',
        patty: 'Chicken',
        cheese: true,
        lettuce: false,
        tomato: true,
        onion: false,
        sauce: true,
        price: 6.99,
        calories: 550,
        inStock: true,
        description: 'Grilled chicken with BBQ sauce, melted cheese, and fresh tomato.'
    },
    {
        id: 6,
        name: 'Mushroom Melt',
        patty: 'Beef',
        cheese: true,
        lettuce: true,
        tomato: false,
        onion: true,
        sauce: true,
        price: 6.49,
        calories: 650,
        inStock: true,
        description: 'A savory beef patty with melted cheese, sautéed mushrooms, and caramelized onions.'
    },
    {
        id: 7,
        name: 'Spicy Deluxe',
        patty: 'Beef',
        cheese: true,
        lettuce: true,
        tomato: true,
        onion: false,
        sauce: true,
        price: 7.49,
        calories: 600,
        inStock: true,
        description: 'A spicy beef patty with cheese, lettuce, tomato, and a special hot sauce.'
    },
    {
        id: 8,
        name: 'Deluxe Veggie',
        patty: 'Veggie',
        cheese: true,
        lettuce: true,
        tomato: true,
        onion: true,
        sauce: true,
        price: 5.99,
        calories: 400,
        inStock: true,
        description: 'A delicious veggie patty with all the fresh toppings and a creamy sauce.'
    },
    {
        id: 9,
        name: 'Chicken Supreme',
        patty: 'Chicken',
        cheese: true,
        lettuce: false,
        tomato: false,
        onion: true,
        sauce: true,
        price: 6.29,
        calories: 480,
        inStock: true,
        description: 'A grilled chicken patty with cheese, onions, and a tangy sauce.'
    },
    {
        id: 10,
        name: 'Texas Burger',
        patty: 'Beef',
        cheese: true,
        lettuce: true,
        tomato: false,
        onion: true,
        sauce: false,
        price: 6.89,
        calories: 550,
        inStock: true,
        description: 'A Texas-style beef burger with cheese, lettuce, onions, and a smoky flavor.'
    },
    {
        id: 11,
        name: 'Double Cheese',
        patty: 'Beef',
        cheese: true,
        lettuce: true,
        tomato: true,
        onion: true,
        sauce: true,
        price: 7.99,
        calories: 750,
        inStock: false,
        description: 'A double stack of beef patties with double cheese and all the fixings.'
    },
    {
        id: 12,
        name: 'Fish Delight',
        patty: 'Fish',
        cheese: false,
        lettuce: true,
        tomato: false,
        onion: true,
        sauce: true,
        price: 5.49,
        calories: 400,
        inStock: true,
        description: 'A crispy fish patty with lettuce, onions, and a tangy sauce.'
    },
    {
        id: 13,
        name: 'Grilled Chicken',
        patty: 'Chicken',
        cheese: false,
        lettuce: true,
        tomato: true,
        onion: false,
        sauce: false,
        price: 5.99,
        calories: 420,
        inStock: true,
        description: 'Grilled chicken with fresh lettuce, tomato, and no sauce for a healthy bite.'
    },
    {
        id: 14,
        name: 'Southwest Burger',
        patty: 'Beef',
        cheese: true,
        lettuce: true,
        tomato: true,
        onion: false,
        sauce: true,
        price: 6.79,
        calories: 650,
        inStock: true,
        description: 'A beef patty with cheese, lettuce, tomato, and a southwestern spicy sauce.'
    },
    {
        id: 15,
        name: 'Veggie Burger',
        patty: 'Veggie',
        cheese: false,
        lettuce: true,
        tomato: true,
        onion: true,
        sauce: false,
        price: 5.29,
        calories: 350,
        inStock: true,
        description: 'A fresh veggie patty with lettuce, tomato, onion, and no sauce.'
    },
    {
        id: 16,
        name: 'BBQ Beef',
        patty: 'Beef',
        cheese: true,
        lettuce: false,
        tomato: true,
        onion: true,
        sauce: true,
        price: 7.49,
        calories: 700,
        inStock: true,
        description: 'A beef patty with BBQ sauce, cheese, onions, and a fresh tomato.'
    },
    {
        id: 17,
        name: 'Chicken Bacon',
        patty: 'Chicken',
        cheese: true,
        lettuce: true,
        tomato: true,
        onion: true,
        sauce: false,
        price: 7.99,
        calories: 750,
        inStock: false,
        description: 'A delicious chicken patty with bacon, cheese, lettuce, tomato, and onion.'
    },
    {
        id: 18,
        name: 'Ultimate Burger',
        patty: 'Beef',
        cheese: true,
        lettuce: true,
        tomato: true,
        onion: true,
        sauce: true,
        price: 8.49,
        calories: 800,
        inStock: true,
        description: 'The ultimate burger with all the toppings and a juicy beef patty.'
    },
    {
        id: 19,
        name: 'Crispy Chicken',
        patty: 'Chicken',
        cheese: false,
        lettuce: true,
        tomato: false,
        onion: true,
        sauce: true,
        price: 5.99,
        calories: 420,
        inStock: true,
        description: 'A crispy chicken patty with onions, lettuce, and tangy sauce.'
    },
    {
        id: 20,
        name: 'Pineapple Burger',
        patty: 'Beef',
        cheese: true,
        lettuce: false,
        tomato: true,
        onion: true,
        sauce: true,
        price: 7.29,
        calories: 600,
        inStock: true,
        description: 'A beef patty with pineapple, cheese, onions, and a savory sauce.'
    }
];